export const IMAGES = {
  logo: require('../images/logo.png'),
  arrowRight: require('./arrowRight.png'),
  arrowLeft:require('./arrowLeft.png'),
  close_eye_icon: require('./close_eye_icon.png'),
  open_eye_icon: require('./open_eye_icon.png'),
  error_icon: require('./erroIcon.png'),
  securityIcon: require('./securityIcon.png'),
  backIcon: require('./backIcon.png'),
  email_icon: require('./email_icon.png'),
  arrow_bottom: require('./arrow_bottom.png'),
  card: require('./card.png'),
  eye: require('./eye.png'),
  hospital: require('./hospital.png'),
  location_pin: require('./location_pin.png'),
  lock: require('./lock.png'),
  mail: require('./mail.png'),
  person: require('./person.png'),
  stethoscope: require('./stethoscope.png'),
  add_patient: require('./add_patient.png'),
  new_request: require('./new_request.png'),
  clipboard: require('./clipboard.png'),
  document_icon: require('./document_icon.png'),
  patients_icon: require('./patients_icon.png'),
  notification_icon: require('./notification_icon.png'),
  tab_home: require('./tab_home.png'),
  tab_profile: require('./tab_profile.png'),
  tab_patients: require('./tab_patients.png'),
  tab_request: require('./tab_request.png'),
  search: require('./search.png'),
  phone: require('./phone.png'),
  forwardIcon:require('./forwardIcon.png'),
  editIcon:require('./editIcon.png'),
  crossIcon:require('./crossIcon.png'),
  bandegeIcon:require('./bandageIcon.png'),
  maskIcon:require('./maskIcon.png'),
  nurseIcon:require("./nurseIcon.png"),
  ivfIcon:require("./ivfIcon.png"),
injectionIcon:require("./injectionIcon.png"),
testTubeIcon:require("./testTubeIcon.png"),
stethoscopeIcon:require("./stethoscopeIcon.png")
};
