export const STRING = {
  // ─── Auth: Welcome ───────────────────────────────────────────
  welcomeTitle: 'Welcome to\nAt-Home',
  welcomeSubtitle: 'Patients to Doctors',
  signIn: 'Sign In',
  createAccount: 'Create Account',

  // ─── Auth: Register ──────────────────────────────────────────
  createYourAccount: 'Create Your Account',
  createAccountSubtitle: 'Please fill in your professional information',
  updateYourProfile: 'Update Your Profile',
  updateProfileSubtitle: 'Update your professional details',
  fName: 'First Name',
  lName: 'Last Name',
  emailAddress: 'Email Address',
  password: 'Password',
  rppsNumber: 'RPPS Number',
  finessNumber: 'FINESS Number',
  specialty: 'Medical Specialty',
  placeOfPractice: 'Place of Practice',
  businessAddress: 'Business Address',
  agreeToTerms: 'I agree to the',
  termsAndConditions: 'Terms & Conditions',
  continue: 'Continue',
  enterFName: 'Enter first name',
  enterLName: 'Enter last name',
  enterEmailAddress: 'Enter email address',
  createPassword: 'Create password',
  enterPassword: 'Enter password',
  createPasswordMessage: "We'll send verification to this email",
  enterRppsNumber: 'Enter RPPS number',
  enterFinessNumber: 'Enter FINESS number',
  elevenDigit: '11 digits',
  nineDigit: '9 digits',
  selectYourSpecialty: 'Select your specialty',
  selectPlaceOfPractice: 'Select place of practice',
  submitRegistration: 'Submit Registration',
  saveChanges: 'Save Changes',
  cancel: 'Cancel',
  enterValidEmail: 'Enter a valid email address',
  passwordRequired: 'Password is required',
  passwordMustBe8To16CharactersWithAtLeast1Uppercase1LowercaseAnd1Number:
    'Password must be 8–16 characters with at least 1 uppercase, 1 lowercase, and 1 number',
  rppsNumberRequired: 'RPPS number is required',
  rppsNumberMustBe11Digits: 'RPPS number must be exactly 11 digits',
  finessNumberRequired: 'FINESS number is required',
  finessNumberMustBe9Digits: 'FINESS number must be exactly 9 digits',
  pleaseSelectYourSpecialty: 'Please select your specialty',
  placeOfPracticeRequired: 'Place of practice is required',
  addressRequired: 'Address is required',
  youMustAcceptTheTermsToContinue: 'You must accept the terms to continue',
  failedToUploadProfileImage: 'Failed to upload profile image',
  updateYourProfessionalDetails: 'Update your professional details',
  weWillSendVerificationToThisEmail: "We'll send verification to this email",
  facilityIdentificationNumber: 'Facility identification number',
  streetAddressCityPostalCode: 'Street address, city, postal code',
  iAgreeToThe: 'I agree to the',
  privacyPolicy: 'Privacy Policy',
  termsOfService: 'Terms of Service',
  and: 'and',
  alreadyHaveAnAccount: "Don't have an account?",
  registrationSuccessful: 'Registration Successful',
  yourAccountHasBeenCreatedAndIsCurrently:
    'Your account has been created and is currently',
  pendingAdminApproval: 'pending admin approval',
  weWillNotifyYouViaEmailOnceYourAccountIsActivated:
    'We will notify you via email once your account is activated',
  whatHappensNext: 'What happens next?',
  yourRegDes: `Your registration will be reviewed by the admin. You will be notified once your account is approved. You cannot log in until your account is approved.`,

  // ─── Auth: Login ─────────────────────────────────────────────
  welcomeBack: 'Welcome Back',
  welcomeBackMessage: 'Sign in to your At-Home account',
  login: 'Login',
  secureEncryptedConnection: 'Secure, encrypted connection',
  dontHaveAnAccount: "Don't have an account?",
  registerHere: 'Register here',
  logInMessage:
    'Note: You cannot log in until your account is approved by admin.',
  emailRequired: 'Email is required',
  invalidEmail: 'Please enter a valid email',
  incorrectPassword: 'Incorrect password. Please try again.',
  forgotPassword: 'Forgot Password',
  forgotQuestion: 'Forgot?',

  // ─── Auth: Forgot Password ───────────────────────────────────
  sendOTP: 'Send OTP / Reset Link',
  forgetPasswordMessage:
    "Enter your registered email address and we'll send you an OTP to reset your password.",
  backToLogin: 'Back to Login',
  passwordsDoNotMatch: 'Passwords do not match.',

  // ─── Auth: OTP Verification ──────────────────────────────────
  verifyEmail: 'Verify your email',
  varifyEmailMessage: 'We sent a 6-digit code to',
  codeExpiresIn: 'Code expires in',
  resendCode: 'Resend Code',
  verify: 'Verify',
  invalidCode: 'Invalid code. Please try again.',

  // ─── Auth: Reset Password ────────────────────────────────────
  resetPassword: 'Reset Password',
  resetPasswordMessage: 'Create a new, strong password for your account.',
  newPassword: 'New Password',
  confirmPassword: 'Confirm Password',
  passwordStrength: 'Password Strength',
  atLeast8Chars: 'At least 8 characters',
  containsUpper: 'Contains uppercase letter',
  containsNumber: 'Contains number',
  containsSpecial: 'Contains special character',
  enterNewPassword: 'Enter new password',
  enterConfirmPassword: 'Enter confirm password',

  // ─── Home Screen ─────────────────────────────────────────────
  goodMorning: 'Good morning,',
  requestsOverview: 'Requests Overview',
  active: 'Active',
  inprogress: 'Inprogress',
  submitted: 'Submitted',
  returned: 'Returned',
  actionRequired: 'Action Required',
  formAwaitingSignature: 'Form Awaiting Signature',
  totalPatients: 'Total Patients',
  patients: 'Patients',
  viewAll: 'View All',
  quickActions: 'Quick Actions',
  newRequest: 'New Request',
  addPatient: 'Add Patient',
  signPendingForm: 'Sign Pending Form',
  recentActivity: 'Recent Activity',
  recentQueue: 'Recent Queue',
  requestId: 'Request ID',
  formStatus: 'Form Status',
  updateAndSign: 'Update & Sign',

  // ─── Doctor Profile ──────────────────────────────────────────
  profile: 'Profile',
  editProfile: 'Edit Profile',
  personalInformation: 'Personal Information',
  professionalCredentials: 'Professional Credentials',
  professionalDetails: 'Professional Details',
  appVersion: 'App Version',
  appVersionValue: 'v2.4.1 (Build 842)',
  logOut: 'Log Out',

  // ─── Add Patient ─────────────────────────────────────────────
  addPatientTitle: 'Add Patient',
  dateOfBirth: 'Date of Birth',
  phoneNumber: 'Phone Number',
  streetAddress: 'Street Address',
  city: 'City',
  zip: 'Zip',
  contactDetails: 'Contact Details',
  address: 'Address',
  medicalInformation: 'Medical Information',
  initialNotes: 'Initial Notes / Allergies',
  savePatient: 'Save Patient',
  notesPlaceholder:
    'Enter any known allergies, chronic conditions, or important medical history...',
  notesHelper: 'Optional. Can be updated later.',
  selectDateOfBirth: 'Select date of birth',
  enterPhoneNumber: 'Enter phone number',
  enterStreetAddress: 'Enter street address',
  enterCity: 'Enter city',
  enterZip: 'Zip',
  searchPatients: 'Search patients...',
  editPatient: 'Edit Patient',
  patientDetail: 'Patient Detail',
  activePatient: 'Active Patient',
  primaryContact: 'Primary Contact',
  homeAddress: 'Home Address',
  medicalNotes: 'Medical Notes',
  edit: 'Edit',
  medicalDescription: 'Medical Description',
  linkedRequests: 'Linked Requests',

  // ─── Patient Request ──────────────────────────────────────────
  createRequest: 'Create Request',
  recent: 'Recent',
  allPatients: 'All Patients',
  activeOnly: 'Active Only',
  step1Of3: 'Step 1/3: Patient',
  step2Of3: 'Step 2/3: Service',
  step3Of3: 'Step 3/3: Fill Medical Form',
  selectService: 'Select Service',
  selectServiceDescription:
    'Choose the primary service required for the patient.',
  p_id: 'ID: #P-',
  yo: 'yo',
  selectPatient: 'Select Patient',
  searchByNameOrId: 'Search by name or ID...',
  noPatientsFound: 'No patients found',
  createNewPatient: 'Create New Patient',

  // ─── Validation / Errors ─────────────────────────────────────
  fNameRequired: 'First name is required.',
  lNameRequired: 'Last name is required.',
  phoneRequired: 'Phone number is required.',
  invalidEmailAddress: 'Please enter a valid email address.',
  invalidDateFormat: 'Use YYYY-MM-DD format.',
  specialtyRequired: 'Please select your specialty.',
  practiceTypeRequired: 'Place of practice is required.',
  rppsRequired: 'RPPS number is required.',
  finessRequired: 'FINESS number is required.',
  nameRequired: 'Name is required.',
  passwordMismatch: 'Passwords do not match.',
  agreementRequired: 'You must agree to the terms.',

  // ─── Forms ─────────────────────────────────────
  antibiotherapyInfusionForm: 'Antibiotherapy Infusion Prescription Form',
  artificialNutritionForm: 'Enteral Artificial Nutrition Prescription Form',
  prescriptionDetails: 'Prescription Details',
  prescriptionDate: 'Prescription Date',
  startOfHomeInfusionTherapy: 'Start of home infusion therapy',
  renewalOrModification: 'Renewal or modification',
  prescriberIdentification: 'Prescriber Identification',
  infusionProducts: 'Infusion Products',
  product: 'Product #',
  nutrient: 'Nutrient #',
  remove: 'Remove',
  productName: 'Product Name',
  enterProductName: 'Enter product name',
  strength: 'Strength',
  concentration: 'Concentration',
  freqPerDay: 'Freq/Day',
  withDiluent: 'With Diluent',
  withoutDiluent: 'Without Diluent',
  diluentVolume: 'Diluent Volume (ml)',
  duration: 'Duration (H)',
  durationMin: 'Duration (M)',
  hours: 'Hrs',
  minutes: 'Min',
  routeOfAccess: 'Route of Access',
  patientMustRemainAmbulatory: 'Patient must remain ambulatory',
  startDate: 'Start Date',
  endDate: 'End Date',
  addAnotherProduct: '+ Add Another Product',
  physicianSignature: 'Physician Signature',

  // ─── CNO Form ─────────────────────────────────────
  cnoForm: 'Clinical Nutrition Order (CNO) Form',
  medicalHistory: 'Medical History & Clinical Context',
  prescriptionContext: 'Prescription Context',
  patientCondition: 'Patient Condition',
  patientAge: 'Patient Age',
  enterPatientAge: 'Enter patient age',
  patientWeightConfirm: 'Patient Weight Confirm',
  enterPatientWeight: 'Enter patient weight',
  primaryDiagnosis: 'Primary Diagnosis',
  prescriptionPlace: 'Prescription Place',
  prescriptionType: 'Prescription Type',
  outSideAld: 'Outside ALD',
  weight: 'Weight',
  nutritionalStatus: 'Nutritional Status',
  progressionOfThePathology: 'Progression of the pathology',
  levelOfSpontaneousOralIntake: 'Level of spontaneous oral intake',
  toleranceOfOralNutritionalSupplements:
    'Tolerance of oral nutritional supplements (ONS)',
  complianceWithOns: 'Compliance with ONS',
  date: 'Date',
  diabeticRange: 'Diabetic Range',
  standardCarbohydrateRange: 'Standard Carbohydrate Range',
  patientName: 'Patient Name',
  relatedToAld: 'Related to ALD',
  enterPatientName: 'Enter patient name',
  enterPrescriptionPlace: 'Enter prescription place',
  comorbidities: 'Comorbidities (Diabetes, Renal Failure, etc.)',
  nutritionalAssessment: 'Nutritional Assessment',
  weightLossPercentage: 'Weight Loss % (last 6 months)',
  bmi: 'BMI (kg/m²)',
  oralIntake: 'Oral Intake',
  normal: 'Normal',
  reduced: 'Reduced',
  minimal: 'Minimal',
  albuminLevel: 'Albumin Level (g/L)',
  albuminDate: 'Date of Albumin Test',
  nutritionalPrescription: 'Nutritional Prescription',
  energyDensity: 'Energy Density (kcal/ml)',
  volumePerDay: 'Volume per Day (ml)',
  frequency: 'Frequency',
  durationWeeks: 'Duration (Weeks)',
  followUp: 'Follow-up',
  weightMonitoringFrequency: 'Weight Monitoring Frequency',
  signature: 'Signature',

  //ANTI-Biotherpy
  youCanOnlyAddUpto10Products: 'You can only add up to 10 products',
  prescriptionDateRequired: 'Prescription date is required',
  lastNameRequired: 'Last name is required',
  firstNameRequired: 'First name is required',
  atLeastOneProductRequired: 'At least one product name is required',
  pleaseFillAllRequiredFields: 'Please fill in all required fields',
  modeOfAdministration: 'Mode of Administration',
  thePatientMustRemainAmbulatoryDuringTreatment:
    'The patient must remain ambulatory during treatment?:',
  yes: 'Yes',
  no: 'No',
  preparedInFacility:
    'If filled/prepared under the supervision of a healthcare facility, tick this box',
  treatmentDurationDays: 'Treatment Duration (days)',
  enterTreatmentDuration: 'Enter treatment duration',
  totalNumberOfInfusions: 'Total Number of Infusions',
  ifThisTreatmentMustBeInfused:
    'If this treatment must be infused ALONE, tick this box',
  addAntibioticProduct: '+ Add Product',

  //ARTIFICIAL NUTRITION
  nutrientsRequired: 'At least one nutrient is required',
  prescriptionPlan: 'Prescription Plan',
  from: 'From',
  prescriptionDurationWeeks: 'Prescription Duration (weeks)',
  weeks: 'Weeks',
  number: 'Number',
  renewalTimes: 'To be renewed (times)',
  treatmentPlan: 'Treatment Plan',
  nutritionDurationWeeks: 'Nutrition Duration (weeks)',
  feedingMode: 'Feeding Mode',
  equipmentAndPackages: 'Equipment & Packages',
  initialSetupPackage: 'Initial Setup Package',
  weeklyPackage: 'Weekly Package',
  nasogastricTubeCh: 'Nasogastric Tube CH',
  enterTubeDetails: 'Enter tube details',
  nasogastricRatePerMonth: 'Nasogastric Rate per Month (ml)',
  enterRate: 'Enter rate',
  jejunostomyTubeCh: 'Jejunostomy Tube CH',
  ivPoleRental: 'IV Pole Rental',
  nasogastricCareFrequencyDays: 'Nasogastric Care Frequency (days)',
  gastrostomyCareEquipment: 'Gastrostomy Care Equipment',
  enterFrequency: 'Enter frequency',
  gastrostomyReplacementEquipment: 'Gastrostomy Replacement Equipment',
  buttonExtensionSet: 'Gastrostomy Button Extension Set',
  jejunostomyCareFrequencyDays: 'Jejunostomy Care Frequency (days)',
  nonAldPrescriptions: 'Non-ALD Prescriptions',
  aldPrescriptions: 'ALD Prescriptions',
  nutrients: 'Nutrients',
  nutrientName: 'Nutrient name',
  ml: 'ml',
  qty: 'qty',
  perDay: 'per day',
  numberOfBoxesChecked: 'Number of boxes checked:',
  weightKg: 'Weight (kg)',
  kg: 'kg',
  nutritionProducts: 'Nutrition Products',
  category: 'Category',
  selectCategory: 'Select Category',
  productType: 'Product Type',
  selectProductType: 'Select Product Type',

  //CNO
  quantityMustBeNumber: 'Quantity must be a number',
  ageMustBeNumber: 'Age must be a number',
  weightMustBeNumber: 'Weight must be a number',
  mustBeNumber: 'Must be a number',
  age: 'Age',
  years: 'Years',
  otherNutrition: 'Other Nutrition',
  enterOtherNutritionDetails: 'Enter other nutrition details',
  instructions: 'Instructions',
  consumeAtLeast2HoursBeforeOrAfterMealsFor1Month:
    'Consume at least 2 hours before or after meals for 1 month',
  texture: 'Texture',
  enterTextureDetails: 'Enter texture details',
  reassessment: 'Reassessment',
  reassessmentAfterMonths: 'Reassessment After (months)',
  renewalMonths: 'Renewal (months)',
  months: 'Months',
  reassessmentCriteria: 'Reassessment Criteria',
  selected: 'selected',

  //generic
  freePrescription: 'Free Prescription',
  additionalNotes: 'Additional Notes',

  recentlyAdded: 'Recently Added',
  recentlyUpdated: 'Recently Updated',
  all: 'All',
  dob: 'DOB:',
};
