export const STRING = {
  welcomeTitle: 'Welcome to\nAt-Home',
  welcomeSubtitle: 'Patients to Doctors',
  signIn: 'Sign In',
  createAccount: 'Create Account',
  createYourAccount: 'Create Your Account',
  createAccountSubtitle: 'Please fill in your professional information',
  fullName: 'Full Name',
  emailAddress: 'Email Address',
  password: 'Password',
  rppsNumber: 'RPPS Number',
  finessNumber: 'FINESS Number',
  specialty: 'Specialty',
  placeOfPractice: 'Place of Practice',
  address: 'Address',
  agreeToTerms: 'I agree to the',
  termsAndConditions: 'Terms & Conditions',
  continue: 'Continue',
  enterFullName: 'Enter full name',
  enterEmailAddress: 'Enter email address',
  createPassword: 'Create password',
  enterPassword: 'Enter password',
  createPasswordMessage: "We'll send verification to this email",
  enterRppsNumber: 'Enter RPPS number',
  enterFinessNumber: 'Enter FINESS number',
  elevenDigit: '11 digits',
  nineDigit: '9 digits',
  selectYourSpecialty: 'Select your specialty',
  submitRegistration: 'Submit Registration',
  welcomeBack: 'Welcome Back',
  welcomeBackMessage: 'Sign in to your At-Home account',
  login: 'Login',
  secureEncryptedConnection: 'Secure, encrypted connection',
  dontHaveAnAccount: "Don't have an account?",
  registerHere: 'Register here',
  logInMessage:
    'Note: You cannot log in until your account is approved by admin.',
  emailRequired: 'Email is required',
  passwordRequired: 'Password is required',
  invalidEmail: 'Please enter a valid email',
  incorrectPassword: 'Incorrect password. Please try again.',
  forgotPassword: 'Forgot Password',
  forgotQuestion: 'Forgot?',
  sendOTP: 'Send OTP / Reset Link',
  forgetPasswordMessage:
    "Enter your registered email address and we'll send you an OTP to reset your password.",
  backToLogin: 'Back to Login',
  verifyEmail: 'Verify your email',
  varifyEmailMessage: 'We sent a 6-digit code to',
  codeExpiresIn: 'Code expires in',
  resendCode: 'Resend Code',
  verify: 'Verify',
  resetPassword: 'Reset Password',
  resetPasswordMessage: 'Create a new, strong password for your account.',
  newPassword: 'New Password',
  confirmPassword: 'Confirm Password',
  passwordStrength: 'Password Strength',
  atLeast8Chars: 'At least 8 characters',
  containsUpper: 'Contains uppercase letter',
  containsNumber: 'Contains number',
  containsSpecial: 'Contains special character',
  goodMorning: 'Good morning,',
  requestsOverview: 'Requests Overview',
  active: 'Active',
  inprogress: 'Inprogress',
  submitted: 'Submitted',
  returned: 'Returned',
  actionRequired: 'Action Required',
  formAwaitingSignature: 'Form Awaiting Signature',
  totalPatients: 'Total Patients',
  patients: 'Patients',
  viewAll: 'View All',
  searchPatients: 'Search patients...',
  quickActions: 'Quick Actions',
  newRequest: 'New Request',
  addPatient: 'Add Patient',
  enterNewPassword: 'Enter new password',
  enterConfirmPassword: 'Enter confirm password',
};
