export const STRING = {
  // ─── Auth: Welcome ───────────────────────────────────────────
  welcomeTitle: 'Welcome to\nAt-Home',
  welcomeSubtitle: 'Patients to Doctors',
  signIn: 'Sign In',
  createAccount: 'Create Account',

  // ─── Auth: Register ──────────────────────────────────────────
  createYourAccount: 'Create Your Account',
  createAccountSubtitle: 'Please fill in your professional information',
  updateYourProfile: 'Update Your Profile',
  updateProfileSubtitle: 'Update your professional details',
  fullName: 'Full Name',
  emailAddress: 'Email Address',
  password: 'Password',
  rppsNumber: 'RPPS Number',
  finessNumber: 'FINESS Number',
  specialty: 'Medical Specialty',
  placeOfPractice: 'Place of Practice',
  businessAddress: 'Business Address',
  agreeToTerms: 'I agree to the',
  termsAndConditions: 'Terms & Conditions',
  continue: 'Continue',
  enterFullName: 'Enter full name',
  enterEmailAddress: 'Enter email address',
  createPassword: 'Create password',
  enterPassword: 'Enter password',
  createPasswordMessage: "We'll send verification to this email",
  enterRppsNumber: 'Enter RPPS number',
  enterFinessNumber: 'Enter FINESS number',
  elevenDigit: '11 digits',
  nineDigit: '9 digits',
  selectYourSpecialty: 'Select your specialty',
  selectPlaceOfPractice: 'Select place of practice',
  submitRegistration: 'Submit Registration',
  saveChanges: 'Save Changes',
  cancel: 'Cancel',

  // ─── Auth: Login ─────────────────────────────────────────────
  welcomeBack: 'Welcome Back',
  welcomeBackMessage: 'Sign in to your At-Home account',
  login: 'Login',
  secureEncryptedConnection: 'Secure, encrypted connection',
  dontHaveAnAccount: "Don't have an account?",
  registerHere: 'Register here',
  logInMessage:
    'Note: You cannot log in until your account is approved by admin.',
  emailRequired: 'Email is required',
  passwordRequired: 'Password is required',
  invalidEmail: 'Please enter a valid email',
  incorrectPassword: 'Incorrect password. Please try again.',
  forgotPassword: 'Forgot Password',
  forgotQuestion: 'Forgot?',

  // ─── Auth: Forgot Password ───────────────────────────────────
  sendOTP: 'Send OTP / Reset Link',
  forgetPasswordMessage:
    "Enter your registered email address and we'll send you an OTP to reset your password.",
  backToLogin: 'Back to Login',

  // ─── Auth: OTP Verification ──────────────────────────────────
  verifyEmail: 'Verify your email',
  varifyEmailMessage: 'We sent a 6-digit code to',
  codeExpiresIn: 'Code expires in',
  resendCode: 'Resend Code',
  verify: 'Verify',

  // ─── Auth: Reset Password ────────────────────────────────────
  resetPassword: 'Reset Password',
  resetPasswordMessage: 'Create a new, strong password for your account.',
  newPassword: 'New Password',
  confirmPassword: 'Confirm Password',
  passwordStrength: 'Password Strength',
  atLeast8Chars: 'At least 8 characters',
  containsUpper: 'Contains uppercase letter',
  containsNumber: 'Contains number',
  containsSpecial: 'Contains special character',
  enterNewPassword: 'Enter new password',
  enterConfirmPassword: 'Enter confirm password',

  // ─── Home Screen ─────────────────────────────────────────────
  goodMorning: 'Good morning,',
  requestsOverview: 'Requests Overview',
  active: 'Active',
  inprogress: 'Inprogress',
  submitted: 'Submitted',
  returned: 'Returned',
  actionRequired: 'Action Required',
  formAwaitingSignature: 'Form Awaiting Signature',
  totalPatients: 'Total Patients',
  patients: 'Patients',
  viewAll: 'View All',
  quickActions: 'Quick Actions',
  newRequest: 'New Request',
  addPatient: 'Add Patient',
  signPendingForm: 'Sign Pending Form',
  recentActivity: 'Recent Activity',
  recentQueue: 'Recent Queue',
  requestId: 'Request ID',
  formStatus: 'Form Status',
  updateAndSign: 'Update & Sign',

  // ─── Doctor Profile ──────────────────────────────────────────
  profile: 'Profile',
  editProfile: 'Edit Profile',
  personalInformation: 'Personal Information',
  professionalCredentials: 'Professional Credentials',
  professionalDetails: 'Professional Details',
  appVersion: 'App Version',
  appVersionValue: 'v2.4.1 (Build 842)',
  termsOfService: 'Terms of Service',
  privacyPolicy: 'Privacy Policy',
  logOut: 'Log Out',

  // ─── Add Patient ─────────────────────────────────────────────
  addPatientTitle: 'Add Patient',
  dateOfBirth: 'Date of Birth',
  phoneNumber: 'Phone Number',
  streetAddress: 'Street Address',
  city: 'City',
  zip: 'Zip',
  contactDetails: 'Contact Details',
  address: 'Address',
  medicalInformation: 'Medical Information',
  initialNotes: 'Initial Notes / Allergies',
  savePatient: 'Save Patient',
  notesPlaceholder:
    'Enter any known allergies, chronic conditions, or important medical history...',
  notesHelper: 'Optional. Can be updated later.',
  selectDateOfBirth: 'Select date of birth',
  enterPhoneNumber: 'Enter phone number',
  enterStreetAddress: 'Enter street address',
  enterCity: 'Enter city',
  enterZip: 'Zip',
  searchPatients: 'Search patients...',
  editPatient: 'Edit Patient',
  patientDetail: 'Patient Detail',
  activePatient: 'Active Patient',
  primaryContact: 'Primary Contact',
  homeAddress: 'Home Address',
  medicalNotes: 'Medical Notes',
  edit: 'Edit',
  medicalDescription: 'Medical Description',
  linkedRequests: 'Linked Requests',

  // ─── Patient Request ──────────────────────────────────────────
  createRequest: 'Create Request',
  recent: 'Recent',
  allPatients: 'All Patients',
  activeOnly: 'Active Only',
  step1Of3: 'Step 1/3: Patient',
  step2Of3: 'Step 2/3: Service',
  step3Of3: 'Step 3/3: Fill Medical Form',
  selectService: 'Select Service',
  selectServiceDescription:
    'Choose the primary service required for the patient.',

  // ─── Validation / Errors ─────────────────────────────────────
  fullNameRequired: 'Full name is required.',
  fullNameMinLength: 'Name must be at least 3 characters.',
  phoneRequired: 'Phone number is required.',
  invalidEmailAddress: 'Please enter a valid email address.',
  invalidDateFormat: 'Use YYYY-MM-DD format.',
  specialtyRequired: 'Please select your specialty.',
  practiceTypeRequired: 'Place of practice is required.',
  addressRequired: 'Business address is required.',
  rppsRequired: 'RPPS number is required.',
  finessRequired: 'FINESS number is required.',
  nameRequired: 'Name is required.',
  passwordMismatch: 'Passwords do not match.',
  agreementRequired: 'You must agree to the terms.',

  // ─── Forms ─────────────────────────────────────
  antibiotherapyInfusionForm: 'Antibiotherapy Infusion Prescription Form',
  artificialNutritionForm: 'Enteral Artificial Nutrition Prescription Form',
  prescriptionDetails: 'Prescription Details',
  prescriptionDate: 'Prescription Date',
  startOfHomeInfusionTherapy: 'Start of home infusion therapy',
  renewalOrModification: 'Renewal or modification',
  prescriberIdentification: 'Prescriber Identification',
  infusionProducts: 'Infusion Products',
  product: 'Product #',
  nutrient: 'Nutrient #',
  remove: 'Remove',
  productName: 'Product Name',
  enterProductName: 'Enter product name',
  strength: 'Strength',
  concentration: 'Concentration',
  freqPerDay: 'Freq/Day',
  withDiluent: 'With Diluent',
  withoutDiluent: 'Without Diluent',
  diluentVolume: 'Diluent Volume (ml)',
  duration: 'Duration (H)',
  durationMin: 'Duration (M)',
  hours: 'Hrs',
  minutes: 'Min',
  routeOfAccess: 'Route of Access',
  patientMustRemainAmbulatory: 'Patient must remain ambulatory',
  startDate: 'Start Date',
  endDate: 'End Date',
  addAnotherProduct: '+ Add Another Product',
  physicianSignature: 'Physician Signature',

  // ─── CNO Form ─────────────────────────────────────
  cnoForm: 'Clinical Nutrition Order (CNO) Form',
  medicalHistory: 'Medical History & Clinical Context',
  prescriptionContext: 'Prescription Context',
  patientCondition: 'Patient Condition',
  patientAge: 'Patient Age',
  enterPatientAge: 'Enter patient age',
  patientWeightConfirm: 'Patient Weight Confirm',
  enterPatientWeight: 'Enter patient weight',
  primaryDiagnosis: 'Primary Diagnosis',
  prescriptionPlace: 'Prescription Place',
  prescriptionType: 'Prescription Type',
  outSideAld: 'Outside ALD',
  weight: 'Weight',
  nutritionalStatus: 'Nutritional Status',
  progressionOfThePathology: 'Progression of the pathology',
  levelOfSpontaneousOralIntake: 'Level of spontaneous oral intake',
  toleranceOfOralNutritionalSupplements:
    'Tolerance of oral nutritional supplements (ONS)',
  complianceWithOns: 'Compliance with ONS',
  date: 'Date',
  diabeticRange: 'Diabetic Range',
  standardCarbohydrateRange: 'Standard Carbohydrate Range',
  patientName: 'Patient Name',
  relatedToAld: 'Related to ALD',
  enterPatientName: 'Enter patient name',
  enterPrescriptionPlace: 'Enter prescription place',
  comorbidities: 'Comorbidities (Diabetes, Renal Failure, etc.)',
  nutritionalAssessment: 'Nutritional Assessment',
  weightLossPercentage: 'Weight Loss % (last 6 months)',
  bmi: 'BMI (kg/m²)',
  oralIntake: 'Oral Intake',
  normal: 'Normal',
  reduced: 'Reduced',
  minimal: 'Minimal',
  albuminLevel: 'Albumin Level (g/L)',
  albuminDate: 'Date of Albumin Test',
  nutritionalPrescription: 'Nutritional Prescription',
  energyDensity: 'Energy Density (kcal/ml)',
  volumePerDay: 'Volume per Day (ml)',
  frequency: 'Frequency',
  durationWeeks: 'Duration (Weeks)',
  followUp: 'Follow-up',
  weightMonitoringFrequency: 'Weight Monitoring Frequency',
  signature: 'Signature',
};
